### ISSUE TITLE
Style with bootstrap

### ISSUE THREAD

**Issue by sonianand11** [MohsinMultani/Blog_Application#4]
Add bootstrap style sheet in application.
download bootstrap from here http://getbootstrap.com/

Tutorial to add bootstrap in rails application
https://launchschool.com/blog/integrating-rails-and-bootstrap-part-1

Modify table tag and add class mentioned in bootstrap
http://getbootstrap.com/css/#tables
http://getbootstrap.com/css/#forms
http://getbootstrap.com/css/#buttons

**Comment by MohsinMultani** [comment]
Invalid CSS after "#efe": expected expression (e.g. 1px, bold), was ";"

This error giving for every style. bcz of ; now how can i solve this. i have not changed anything in this file.

**Comment by sonianand11** [comment]
Try to use this gem
http://railscasts.com/episodes/328-twitter-bootstrap-basics
See this video tutorial
http://railscasts.com/episodes/328-twitter-bootstrap-basics

**Comment by MohsinMultani** [comment]
Done with all modification in Bootstrap.
