### ISSUE TITLE
Add paperclip gem

### ISSUE THREAD

**Issue by sonianand11** [MohsinMultani/Blog_Application#5]
Add paperclip gem in application
https://github.com/thoughtbot/paperclip

Read link to know how to use gem and add field in table

Add image field in blog. User can select image while creating blog. When user show the blog image should display.
e.g. localhost:3000/blogs/3 in this the image will be displayed.

**Comment by MohsinMultani** [comment]
Adding paperclip gem done.
also aplied in project.

**Comment by MohsinMultani** [comment]
Adding the filed and showing on show image display done.
